name: chat_lasitha
description: This is the demo for chat app by Flutter

publish_to: 'none'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.3
  firebase_core: 1.5.0
  firebase_auth: 3.0.2
  google_sign_in: 5.0.7
  cloud_firestore:  2.5.0
  fluttertoast: 8.0.8
  image_picker: 0.8.3
  shared_preferences: 2.0.6
  firebase_storage: 10.0.2
  intl: 0.17.0
  firebase_messaging: 10.0.5
  flutter_local_notifications: 8.1.1
  photo_view: 0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"